name: chatapp
description: "A new Flutter project."
version: 1.0.0+1
environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # for using cupertino icons
  cupertino_icons: ^1.0.2

  # state management user
  get: ^4.6.6

  # for animation  user
  lottie: ^3.1.0

  # for Handling google sign in
  google_sign_in: ^6.2.1

  # for Api calling Method
  dio: ^5.4.1

  # for LocalDatabase Store
  shared_preferences: ^2.2.2

  # for Integrating firebase
  firebase_core: ^2.27.0

  # for Handling firebase authentication_
  firebase_auth: ^4.16.0

  # for accessing Cloud fireStore database
  cloud_firestore: ^4.15.8

  # for accessing firebase storage upload file
  firebase_storage: ^11.6.9

  # for accessing firebase use Notification
  firebase_messaging: ^14.7.19

  # for Unike name
  uuid: ^4.3.3

  # for showing Emoji
  emoji_picker_flutter: ^2.1.0

  # for firebase storage upload file
  image_picker: ^1.0.7

  # for network Image Show
  cached_network_image: ^3.3.1

  # for show dataTime Format
  intl: ^0.19.0

  # for appIcon set
  flutter_launcher_icons: ^0.11.0

  # for appName set
  flutter_app_name: ^0.1.0

dev_dependencies:
  build_runner:
  flutter_lints:
  flutter_test:
    sdk: flutter
flutter_launcher_icons: any
flutter_icons:
  android: true
  ios: true
  image_path: "assets/img/chatIcon.png"
flutter_app_name:
  name: "chatApp"

  flutter_lints: ^2.0.0
flutter:

  uses-material-design: true


  assets:
    - assets/
    - assets/img/
    - assets/animation/
