// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9VS9tGO3p8f6qGwGfkO7I7dMtBPKkdLQ',
    appId: '1:998814899559:web:cb5cd0a3712891cb47e3c2',
    messagingSenderId: '998814899559',
    projectId: 'chatapp-8cc23',
    authDomain: 'chatapp-8cc23.firebaseapp.com',
    storageBucket: 'chatapp-8cc23.appspot.com',
    measurementId: 'G-DKJ93BCJX3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRtv7gLFVYFEEtQTxYMRsIKS7CFBtS3gI',
    appId: '1:998814899559:android:3631d85f6b35cbff47e3c2',
    messagingSenderId: '998814899559',
    projectId: 'chatapp-8cc23',
    storageBucket: 'chatapp-8cc23.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUdjs8D4RVaR-eAxF7fHElpMNY3v-NVbo',
    appId: '1:998814899559:ios:4860b0789775ac7e47e3c2',
    messagingSenderId: '998814899559',
    projectId: 'chatapp-8cc23',
    storageBucket: 'chatapp-8cc23.appspot.com',
    iosClientId: '998814899559-jh3vg7dao6m1m3cvl4jclvvjg7vug7qm.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
